import pandas as pd

def create_contacts_entry(account_input_dictionary, contacts_id):

    #If not household, create one contacts row, else create two contacts rows.
    contact_row_entry = pd.DataFrame.from_dict({
        'id': [contacts_id],
        'is_deleted' : [0],
        'account_id': [account_input_dictionary[id]],
        'salutation': [0], 
        'first_name': [0],
        'last_name': [0],
        'other_street': [0],	
        'other_city': [0],
        'other_state': [0],
        'other_postal_code': [0],
        'other_country': [0],
        'mailing_street': [0],
        'mailing_city': [0],
        'mailing_state': [0],
        'mailing_postal_code': [0],
        'mailing_country': [0],
        'phone': [0],
        'fax': [0],
        'mobile_phone': [0],
        'home_phone': [0],
        'other_phone': [0],
        'email': [0],
        'title': [0],
        'department': [0],
        'birthdate': [0],	
        'description': [0],
        'has_opted_out_of_email': [0],
        'has_opted_out_of_fax': [0],
        'do_not_call': [0],
        'created_date': [0],
        'created_by_id': [0],
        'last_modified_date': [0],
        'last_modified_by_id': [0],
        'system_mod_stamp': [0],
        'last_activity_date': [0],
        'email_bounce_reason': [0],
        'email_bounce_date': [0],
        'pronouns': [0],
        'gender_identity': [0],
        'donate_date_entered': [0],
        'deceased': [0],
        'do_not_mail': [0],
        'donor_recognition': [0],
        'formal_salutation': [0],
        'informal_address_name': [0],
        'informal_salutation': [0],
        'volunteer_interests': [0],
        'other_email': [0],
        'company': [0],
        'middle_name': [0],
        'suffix': [0],
        'contact_origin': [0],
        'email_status': [0],	
        'current_season_subscriber': [0],
        'email_lists': [0],
        'board_member': [0],
        'seating_accomodation': [0],
        'reserved_seating': [0],	
        'attending_next_dinner': [0],
        'chocolate_and_card': [0],
        'legacy_membership_circle': [0],
        'email_list_notes': [0]
    })